Controllers/MedicineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

using QSProject.Data.Models;
using QSProject.Data.Services;
using QSProject.Models;


namespace QSProject.Controllers
{
    [Authorize]
    public class MedicineController : BaseController
    {
        private readonly IMedicineService svc;

        // configured via DI
        public MedicineController(IMedicineService ms)
        {
            svc = ms;
        }

        public IActionResult Search()
        {
            return View("LitSearch");
        }

        // GET /medicine/index
        public IActionResult Index()
        {
            // retrieve all OPEN medicine requests
            var search = new MedicineSearchViewModel
            {
                Medicines = svc.SearchMedicineRequests(MedicineRange.OPEN, "")
            };

            return View(search);
        }

        // POST /medicine/index
        [HttpPost]
        public IActionResult Index(MedicineSearchViewModel search)
        {
            // perform search request and assign results to viewmodel Medicine Requests property
            search.Medicines = svc.SearchMedicineRequests(search.Range, search.Request);

            // build custom alert message if post
            var alert = $"{search.Medicines.Count} result(s) found searching '{search.Range}' medicine requests.";
            if (search.Request != null && search.Request != "")
            {
                alert += $" for '{search.Request}'";
            }

            // display custom info alert
            Alert(alert, AlertType.Info);

            return View("Index", search);
        }

        // GET /medicine/{id}
        public IActionResult Details(int id)
        {
            var medicine = svc.GetMedicineRequest(id);

            if (medicine == null)
            {
                Alert("Medicine request not found", AlertType.Warning);
                return RedirectToAction(nameof(Index));
            }

            return View(medicine);
        }

        // POST /medicine/close/{id}
        [HttpPost]
        [Authorize(Roles="staff")]
        public IActionResult Close([Bind("Id, Resolution")] Medicine m)
        {
            // close medicine request via service
            var medicine = svc.CloseMedicineRequest(m.Id, m.Resolution);

            if (medicine == null)
            {
                Alert("Medicine request not found", AlertType.Warning);
            }
            else
            {
                Alert($"Medicine request {m.Id} closed", AlertType.Info);
            }

            // redirect to index view

            return RedirectToAction(nameof(Index));
        }

        // GET /medicine/create
        [Authorize(Roles="patient")]
        public IActionResult Create()
        {
            var patients = svc.GetPatients();

            // populate view model select list property
            var mvm = new MedicineRequestCreateViewModel
            {
                Patients = new SelectList(patients, "Id", "Name")
            };

            // render blank form
            return View(mvm);
        }

        // POST /medicine/create
        [HttpPost]
        [Authorize(Roles ="patient")]
        public IActionResult Create(MedicineRequestCreateViewModel mvm)
        {
            if (ModelState.IsValid)
            {
                svc.CreateMedicineRequest(mvm.PatientId, mvm.MedicineName);

                Alert($"Medicine request created", AlertType.Info);
                return RedirectToAction(nameof(Index));
            }

            // redisplay the form for editing

            return View(mvm);
        }
        


    }
}

Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Authorization;

using QSProject.Data.Models;
using QSProject.Data.Services;
using QSProject.Models;

namespace QSProject.Controllers
{
    [Authorize]
    public class PatientController : BaseController
    {
        private IMedicineService svc;

        // Configured via DI
        public PatientController(IMedicineService ms)
        {
            svc = ms;
        }

        // GET /patient/index
        public IActionResult Index()
        {
            var patients = svc.GetPatients();

            return View(patients);
        }

        // GET /patient/details/{id}
        public IActionResult Details(int id)
        {
            // retrieve the patient with the specified id from the service
            var patient = svc.GetPatient(id);

            if (patient == null)
            {
                Alert("Patient not found", AlertType.Warning);
                return RedirectToAction(nameof(Index));
            }

            return View(patient);
        }

        // GET /patient/create
        [Authorize(Roles = "patient, staff")]
        public IActionResult Create()
        {
            // display blank form to create a patient
            var patient = new Patient();
            return View(patient);
        }

        // POST /patient/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "patient, staff")]
        public IActionResult Create([Bind("Name, Age, Email, PhotoUrl")] Patient p)
        {
            // check email is unique for this patient
            if (svc.IsDuplicateEmail(p.Email, p.Id))
            {
                // add manual validatione error
                ModelState.AddModelError(nameof(p.Email), "The email address is already in use.");
            }

            // validate patient
            if (ModelState.IsValid)
            {
                // pass data to service to store
                var added = svc.AddPatient(p.Name, p.Age, p.Email, p.PhotoUrl);
                Alert("Patient created successfully", AlertType.Info);

                return RedirectToAction(nameof(Index));
            }

            // redisplay the form for editing as there are validation errors
            return View(p);
        }

        // GET /patient/edit/{id}
        [Authorize(Roles = "patient")]
        public IActionResult Edit(int id)
        {
            // load the patient using the service
            var p = svc.GetPatient(id);

            if (p == null)
            {
                Alert($"No such patient {id}", AlertType.Warning);
                return RedirectToAction(nameof(Index));
            }

            // pass patient to view for editing
            return View(p);
        }

        // POST /patient/edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "patient")]
        public IActionResult Edit(int id, [Bind("Id, Name, Age, Email, PhotoUrl")] Patient p)
        {
            // check email is unique for this patient
            if (svc.IsDuplicateEmail(p.Email, p.Id))
            {
                // add manual validation error
                ModelState.AddModelError(nameof(p.Email), "The email address is already in use.");
            }

            // validate patient
            if (ModelState.IsValid)
            {
                // pass data to service to update
                svc.UpdatePatient(p);
                Alert("Patient details saved", AlertType.Info);

                return RedirectToAction(nameof(Index));
            }

            // redisplay the form for editing as validation errors
            return View(p);
        }

        // GET /patient/delete/{id}
        [Authorize(Roles = "patient")]
        public IActionResult Delete(int id)
        {
            // load the patient using the service
            var p = svc.GetPatient(id);

            if (p == null)
            {
                Alert("Patient not found", AlertType.Warning);
                return RedirectToAction(nameof(Index));
            }

            // pass patient to view for deletion confirmation
            return View(p);
        }

        // POST /patient/delete/{id}
        [HttpPost]
        [Authorize(Roles = "patient")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(int id)
        {
            // delete patient via service
            svc.DeletePatient(id);

            Alert($"Patient {id} deleted successfully", AlertType.Success);

            // redirect to the index view
            return RedirectToAction(nameof(Index));
        }

        // GET /patient/createmedicinerequest
        [Authorize(Roles = "patient")]
        public IActionResult CreateMedicineRequest(int id)
        {
            var p = svc.GetPatient(id);

            if (p == null)
            {
                Alert($"Not such patient {id}", AlertType.Warning);
                return RedirectToAction(nameof(Index));
            }

            // create the medicine request view model and populate the PatientId property
            var m = new MedicineRequestCreateViewModel
            {
                PatientId = id
            };

            return View("CreateMedicineRequest", m);
        }

        // POST /patient/createmedicinerequest
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="patient")]
        public IActionResult CreateMedicineRequest([Bind("PatientId, MedicineName")] MedicineRequestCreateViewModel m)
        {
            var p = svc.GetPatient(m.PatientId);

            if (p == null)
            {
                Alert($"No such patient {m.PatientId}", AlertType.Warning);
                return RedirectToAction(nameof(Index));
            }

            // create the medicine request view model and populate the PatientId property
            svc.CreateMedicineRequest(m.PatientId, m.MedicineName);
            Alert($"Medicine request submitted successfully", AlertType.Success);

            return RedirectToAction("Details", new { Id = m.PatientId });
        }

        // GET /patient/search/{request}
        public IActionResult Search(string request)
        {
            var results = svc.GetPatientsMedicineRequest(m => m.Name != null && m.Name.ToLower().Contains(request.ToLower()));

            return View("Index", results);
        }


    }
   
        
    }

Views/Shared/_Alert.cshtml
@{ 
    var message = TempData["Alert.Message"] ?? null;
    var type = TempData["Alert.Type"] ?? null;
}

@if (message != null)
            {
                <div class="alert alert-@type alert-dismissible fade show" role="alert" >
                    @message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
            }

Views/Shared/_Breadcrumbs.cshtml
@model IList<(string, string)>

@if (Model != null)
            {
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        @foreach (var (link, crumb) in Model)
                {
                    @if (link == null || link.Length == 0)
                    {
                        <li class="breadcrumb-item active" aria-current="page">@crumb</li>
                    }
                    else 
                    { 
                        <li class="breadcrumb-item"><a href="@link">@crumb</a></li>
                    }
                }
                    </ol>
                </nav>
            }

Views/Shared/_Carousel.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/lib/Images/Intro.png" data-color="lightblue" alt="QuickScripts">
        </div>

        <div class="carousel-item">
            <img class="d-block w-100" src="~/lib/Images/PillBox.png" data-color="lightblue" alt="Pillbox">
        </div>
    </div>
    <!-- Controls -->
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/_CarouselPatient.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/lib/Images/Patient_Welcome.png" data-color="lightblue" alt="PatientWelcome">
        </div>

        <div class="carousel-item">
            <img class="d-block w-100" src="~/lib/Images/Patient_Follow.png" data-color="lightblue" alt="PatientFollow">
        </div>
    </div>
    <!-- Controls -->
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/_CarouselStaff.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/lib/Images/Staff.png" data-color="lightblue" alt="StaffWelcome">
        </div>

    </div>
    <!-- Controls -->
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="https://img.icons8.com/color/24/000000/pill.png" type="image/x-icon"/>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Quick Scripts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <partial name="_Nav" />
    </header>

    <div class="container">

        <partial name="_Alert" />

        <main role="main" class="pb-2">
            @RenderBody()

        </main>


    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Quick Scripts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_Login.cshtml
<!-- AMC Login partial to display links on nav bar -->
<!-- Logged in -->
<div class="navbar-nav" asp-condition="@User.Identity.IsAuthenticated">
    <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi-person-fill"></i> @User.Identity.Name
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            
            <form asp-controller="User" asp-action="Logout">
                <button type="submit" class="dropdown-item btn btn-link"><i class="bi bi-person-dash-fill"></i> Logout</button>
            </form>
        </div>
    </div>
</div>

<!-- Not Logged in -->
<div class="navbar-nav" asp-condition="@(!User.Identity.IsAuthenticated)">
    <a class="nav-link text-dark" asp-controller="User" asp-action="Login">Login</a>
    <a class="nav-link text-dark" asp-controller="User" asp-action="Register">Register</a>
</div>

Views/Shared/_Nav.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/lib/Blue and Green Medical Logo2.png">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

            <!---Login / Register nav items-->
            <partial name="_Login"/>

            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home"
                       asp-action="Index">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Patient"
                       asp-action="Index">Patients</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Medicine"
                       asp-action="Index">Prescriptions</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home"
                       asp-action="About">About</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Home"
                       asp-action="Privacy">Privacy</a>
                </li>

               
            </ul>

        </div>
    </div>
</nav>